mapping = {
    "eventnb": "eventNumber",
    "jet_LabDr_HadF": "HadronConeExclTruthLabelID",
    "jet_ip2_cu": "IP2D_cu",
    "e_frac_vtx1": "secondaryVtx_EFrac",
    "nTrk_vtx1": "secondaryVtx_nTrks",
    "jet_jf_nvtx": "JetFitter_nVTX",
    "jet_jf_nvtx1t": "JetFitter_nSingleTracks",
    "jet_sv1_n2t": "SV1_N2Tpair",
    "e_first_vtx": "secondaryVtx_E",
    "jet_sv1_efc": "SV1_efracsvx",
    "jet_jf_m": "JetFitter_mass",
    "jet_sv1_Lxy": "SV1_Lxy",
    "JF_Lxy1": "secondaryVtx_Lxy",
    "vtx1_MaxTrkRapidity": "secondaryVtx_max_trk_flightDirRelEta",
    "jet_sv1_deltaR": "SV1_deltaR",
    "MaxTrkRapidity": "max_trk_flightDirRelEta",
    "jet_sv1_ntrkv": "SV1_NGTinSvx",
    "jet_pt": "pt_uncalib",
    "MinTrkRapidity": "min_trk_flightDirRelEta",
    "jet_jf_efc": "JetFitter_energyFraction",
    "jet_ip2": "IP2D_bu",
    "jet_ip3": "IP3D_bu",
    "closestVtx_L3D": "secondaryVtx_L3d",
    "jet_ip2_c": "IP2D_bc",
    "jet_ip3_c": "IP3D_bc", "mass_first_vtx": "secondaryVtx_m",
    "jet_sv1_L3d": "SV1_L3d",
    "jet_eta": "abs_eta_uncalib",
    "vtx1_AvgTrkRapidity": "secondaryVtx_avg_trk_flightDirRelEta",
    "jet_jf_sig3d": "JetFitter_significance3d",
    "vtx1_MinTrkRapidity": "secondaryVtx_min_trk_flightDirRelEta",
    "AvgTrkRapidity": "avg_trk_flightDirRelEta",
    "jet_sv1_m": "SV1_masssvx",
    "jet_jf_dR": "JetFitter_deltaR",
    "jet_sv1_sig3d": "SV1_significance3d",
    "jet_jf_n2t": "JetFitter_N2Tpair",
    "jet_jf_ntrkAtVx": "JetFitter_nTracksAtVtx",
    "jet_ip3_cu": "IP3D_cu", 
    "FCalEt": "FCalEt"
}

var_conv_oldDl1 = {
    "eventnb": "eventNumber",
    "label": "HadronConeExclTruthLabelID",
    "ip2_cu": "IP2D_cu",
    "e_frac_vtx1": "secondaryVtx_EFrac",
    "rnnip_pb": "rnnip_pb",
    "rnnip_pc": "rnnip_pc",
    "nTrk_vtx1": "secondaryVtx_nTrks",
    "jf_nvtx": "JetFitter_nVTX",
    "jf_nvtx1t": "JetFitter_nSingleTracks",
    "sv1_n2t": "SV1_N2Tpair",
    "rnnip_pu": "rnnip_pu",
    "e_first_vtx": "secondaryVtx_E",
    "rnnip_ptau": "rnnip_ptau",
    "sv1_efrc": "SV1_efracsvx",
    "jf_mass": "JetFitter_mass",
    "sv1_Lxy": "SV1_Lxy",
    "JF_Lxy1": "secondaryVtx_Lxy",
    "mu_dR": "SMT_dR",
    "vtx1_MaxTrkRapidity":
    "secondaryVtx_max_trk_flightDirRelEta",
    "sv1_dR": "SV1_deltaR",
    "MaxTrkRapidity": "max_trk_flightDirRelEta",
    "sv1_ntkv": "SV1_NGTinSvx",
    "mu_scatneighsignif": "SMT_scatneighsignif",
    "pt_uCalib": "pt_uncalib",
    "MinTrkRapidity": "min_trk_flightDirRelEta",
    "jf_efrc": "JetFitter_energyFraction",
    "mu_d0": "SMT_mu_d0",
    "ip2": "IP2D_bu",
    "ip3": "IP3D_bu",
    "closestVtx_L3D": "secondaryVtx_L3d",
    "ip2_c": "IP2D_bc",
    "mu_mombalsignif": "SMT_mombalsignif",
    "ip3_c": "IP3D_bc", "mass_first_vtx": "secondaryVtx_m",
    "sv1_L3d": "SV1_L3d",
    "eta_abs_uCalib": "abs_eta_uncalib",
    "mu_pTrel": "SMT_pTrel",
    "mu_qOverPratio": "SMT_qOverPratio",
    "vtx1_AvgTrkRapidity": "secondaryVtx_avg_trk_flightDirRelEta",
    "jf_sig3": "JetFitter_significance3d",
    "vtx1_MinTrkRapidity": "secondaryVtx_min_trk_flightDirRelEta",
    "AvgTrkRapidity": "avg_trk_flightDirRelEta",
    "sv1_mass": "SV1_masssvx",
    "jf_dR": "JetFitter_deltaR",
    "sv1_sig3": "SV1_significance3d",
    "jf_n2tv": "JetFitter_N2Tpair",
    "jf_ntrkv": "JetFitter_nTracksAtVtx",
    "ip3_cu": "IP3D_cu"
}
